packages:
  - "configs/*"
  - "packages/*"
  - "docs/*"
  - "cli/*"
  - "apps/playground"
  - "server/**/*"

catalog:
  # ===========================================
  # 🛠️ 开发工具与构建工具
  # ===========================================
  "turbo": latest
  "vite": ^6.3.5
  "vitest": ^3.2.0
  "@vitest/coverage-v8": ^2.1.8
  "@vitest/ui": ^2.1.8
  "typescript": ~5.7.2
  "tslib": ^2.8.1
  "vue-tsc": ~1.8.8
  "unbuild": ^3.5.0
  "cross-env": ^7.0.3
  "esno": ^0.17.0
  "npm-run-all": ^4.1.5
  "shx": ^0.3.4
  "dotenv": ^16.4.5

  # ===========================================
  # 📦 打包与构建插件
  # ===========================================
  "rollup": ~4.29.1
  "@rollup/plugin-terser": ^0.4.4
  "@rollup/plugin-typescript": ^12.1.2
  "@rollup/plugin-commonjs": ^28.0.2
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^16.0.0
  "@vitejs/plugin-vue": ^5.2.1
  "@vitejs/plugin-vue-jsx": ^4.1.1
  "vite-plugin-compression2": ^1.3.3
  "vite-plugin-dts": ^4.4.0
  "vite-plugin-pwa": ^1.0.0
  "vite-plugin-vue-mcp": latest
  "vite-plugin-vue-devtools": ^7.7.2

  # ===========================================
  # 🔧 代码质量与格式化
  # ===========================================
  "eslint": ~8.57.0
  "eslint-config-turbo": ^2.3.3
  "eslint-plugin-vue": ^9.32.0
  "@typescript-eslint/eslint-plugin": ^8.18.2
  "@typescript-eslint/parser": ^8.18.2
  "lint-staged": ^15.2.10
  "husky": ^9.1.6

  # ===========================================
  # 📝 提交规范
  # ===========================================
  "@commitlint/cli": ^19.5.0
  "@commitlint/config-conventional": ^19.5.0
  "commitlint-plugin-function-rules": ^4.0.1
  "czg": ^1.10.1
  "cz-git": ^1.10.1
  "@changesets/cli": ^2.27.7

  # ===========================================
  # 🎯 Vue 生态系统
  # ===========================================
  "vue": ^3.5.17
  "vue-router": ^4.5.0
  "vue-types": ^6.0.0
  "pinia": ^3.0.0
  "@vue/test-utils": ^2.4.6

  # ===========================================
  # 🚀 Nuxt 生态系统
  # ===========================================
  "nuxt": ^3.17.5
  "@nuxt/kit": ^3.17.5
  "@nuxt/module-builder": ^1.0.1
  "@nuxt/schema": ^3.17.5
  "@nuxt/devtools": ^2.5.0
  "@ant-design-vue/nuxt": ^1.4.6
  "@vite-pwa/nuxt": ^1.0.4
  "@pinia/nuxt": ^0.11.0

  # ===========================================
  # 🎨 UI 组件库
  # ===========================================
  "ant-design-vue": ~4.2.6
  "@ant-design/icons-vue": ^7.0.1
  "unplugin-vue-components": ^28.7.0

  # ===========================================
  # 🎯 样式处理
  # ===========================================
  "sass": ~1.83.0
  "sass-migrator": ^2.2.1
  "less": ^4.2.1
  "postcss-pxtorem": ^6.1.0
  "csstype": ^3.1.2

  # ===========================================
  # 📊 监控与分析
  # ===========================================
  "@sentry/vue": ^8.47.0
  "@sentry/cli": 1.72.0
  "@sentry/vite-plugin": ^2.22.0

  # ===========================================
  # 🛠️ 工具库
  # ===========================================
  "lodash-es": ^4.17.21
  "dayjs": ^1.11.7
  "axios": ^1.7.2
  "qs": ^6.12.2
  "crypto-js": ^4.2.0
  "magic-string": ^0.30.0
  "unplugin": ^2.1.0
  "fs-extra": ^11.2.0
  "sortablejs": ^1.15.0
  "echarts": ^5.6.0
  "highlight.js": ^11.4.0
  "nprogress": 0.2.0
  "element-resize-detector": 1.2.4
  "workbox-build": ^7.3.0
  "workbox-window": ^7.3.0

  # ===========================================
  # 🤖 AI 与自动化
  # ===========================================
  "openai": ^4.86.1
  "@larksuiteoapi/node-sdk": ^1.45.0
  "@modelcontextprotocol/sdk": ^1.8.0
  "zod": ^3.24.2

  # ===========================================
  # 📝 编辑器支持
  # ===========================================
  "monaco-editor": ^0.52.2
  "tinymce": ^5.10.9

  # ===========================================
  # 🧪 测试工具
  # ===========================================
  "jsdom": ^25.0.1

  # ===========================================
  # 📖 文档工具
  # ===========================================
  "vitepress": 1.5.0

  # ===========================================
  # 🌐 服务器相关
  # ===========================================
  "express": ^5.0.1

  # ===========================================
  # 🔍 CLI 工具
  # ===========================================
  "kolorist": ^1.8.0
  "minimist": ^1.2.5
  "prompts": ^2.4.2

  # ===========================================
  # 📋 类型定义
  # ===========================================
  "@types/node": ~20.2.5
  "@types/postcss-pxtorem": ^6.0.3
  "@types/sortablejs": ^1.15.0
  "@types/crypto-js": ^4.2.0
  "@types/lodash-es": ^4.17.12
  "@types/qs": ^6.9.15
  "@types/nprogress": 0.2.0
  "@types/element-resize-detector": 1.1.3
  "@types/fs-extra": ^11.0.4
  "@types/minimist": ^1.2.3
  "@types/prompts": ^2.4.6
