/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    QAntdDrawer: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdDrawer']
    QAntdForm: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdForm']
    QAntdIcon: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdIcon']
    QAntdKeepAliveTabs: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdKeepAliveTabs']
    QAntdSearch: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdSearch']
    QAntdSetting: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdSetting']
    QAntdTable: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdTable']
    QAntdTableAction: typeof import('@quantum-design/vue3-antd-pc-ui/es')['QAntdTableAction']
    QBreadcrumb: typeof import('@quantum-design/vue3-pc-ui/es')['QBreadcrumb']
    QDropdown: typeof import('@quantum-design/vue3-pc-ui/es')['QDropdown']
    QIcon: typeof import('@quantum-design/vue3-pc-ui/es')['QIcon']
    QLoading: typeof import('@quantum-design/vue3-pc-ui/es')['QLoading']
    QmAside: typeof import('./src/components/layout/qm-aside.vue')['default']
    QmHeader: typeof import('./src/components/layout/qm-header.vue')['default']
    QmReloadPrompt: typeof import('./src/components/layout/qm-reload-prompt.vue')['default']
    QThemeModeButton: typeof import('@quantum-design/vue3-pc-ui/es')['QThemeModeButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
