export type ComponentType =
  | 'Input'
  | 'InputNumber'
  | 'Select'
  | 'SelectAll'
  | 'AutoComplete'
  | 'Checkbox'
  | 'Switch'
  | 'DatePicker'
  | 'TimePicker'
  | 'RadioGroup'
  | 'RadioButtonGroup'
  | 'MonthPicker'
  | 'RangePicker'
  | 'WeekPicker'
  | 'Button'
